from tkinter import *
def submit():
    name_name=str(name_entry.get())
    phone_phone=int(phone_entry.get())
    address_address=str(address_entry.get())
    age_age=int(age_entry.get())
    gen= "You selected the option " +str(radio.get())
    
    gender.config(text=gen)  
    name.config(text=name_name)
    phone.config(text=phone_phone)
    address.config(text=address_address)
    age.config(text=age_age)
    
top=Tk()
radio=IntVar()
top.geometry('500x500')
top.title("Registration form")
title=Label(top, text="REGISTRATION FORM",fg="red")
title.place(x=180,y=40)
name=Label(top, text="Enter Full name : ")
name.place(x=20,y=100)
name_entry=Entry(top)
name_entry.place(x=20,y=120)
phone_label=Label(top, text="Enter phone number :  ")
phone_label.place(x=20,y=140)
phone_entry=Entry(top)
phone_entry.place(x=20,y=160)
address_label=Label(top, text="Enter address : ")
address_label.place(x=20,y=180)
address_entry=Entry(top)
address_entry.place(x=20,y=200)
gender_label=Label(top,text="Gender :")
gender_label.place(x=20,y=220)
gender_button1=Radiobutton(top,text="Male",variable=radio,value="1",command=submit)
gender_button1.place(x=60,y=240)
gender_button2=Radiobutton(top,text="Female",variable=radio,value="2",command=submit)
gender_button2.place(x=120,y=240)
age_label=Label(top,text="Age :")
age_label.place(x=20,y=260)
age_entry=Entry(top,width=5)
age_entry.place(x=20,y=280)
submit=Button(top,text="Submit",command=submit)
submit.place(x=20,y=320)
ff=Label(top,text="------------------------------------------------------------------------------------------------------------------------------------------------",fg="blue")
ff.place(x=1,y=360)
result=Label(top,text="Result")
result.place(x=200,y=380)

name_1=Label(top,text="Name :")
name_1.place(x=20,y=400)
name=Label(top,text="",bg="gray")
name.place(x=120,y=400)
phone_1=Label(top,text="Phone :")
phone_1.place(x=20,y=420)
phone=Label(top,text="",bg="gray")
phone.place(x=120,y=420)
address_1=Label(top,text="Address :")
address_1.place(x=20,y=440)
address=Label(top,text="",bg="gray")
address.place(x=120,y=440)
gender_1=Label(top,text="Gender :")
gender_1.place(x=20,y=460)
gender=Label(top,text="",bg="gray")
gender.place(x=120,y=460)
age_1=Label(top,text="Age :")
age_1.place(x=20,y=480)
age=Label(top,text="",bg="gray")
age.place(x=120,y=480)

top.mainloop()
